### ISSUE TITLE
What is the license for Miniswig?

### ISSUE THREAD

**Issue by UbuntuJackson** [WindstilleTeam/miniswig#3]
There is no license explicitly attached to the repository.
Can any copyright holder comment on this? What are the conditions to use and distribute your code?

**Comment by Grumbel** [comment]
It's GPLv3+, the code is a merger from what was floating around in the SuperTux and Windstille repositories. Proper copyright headers will follow in a sec.

**Comment by UbuntuJackson** [comment]
In a sec?

**Comment by UbuntuJackson** [comment]
Hey, I was not quite done. I need you to elaborate.
